export const ISSUES_FETCHING_START = 'ISSUES_FETCHING_START'
export const ISSUES_FETCHING_END = 'ISSUES_FETCHING_END'
export const SINGLE_ISSUE_FETCHING_START = 'SINGLE_ISSUE_FETCHING_START'
export const SINGLE_ISSUE_FETCHING_END = 'SINGLE_ISSUE_FETCHING_END'
